import type { SourceCatalogEntry } from '../src/lib/schema';

const rawSourceCatalog: SourceCatalogEntry[] = [
  {
    id: 'nbc-healthcare-hub',
    provider: 'National Bank',
    title: 'Healthcare professions hub',
    category: 'banking',
    subcategory: 'profession hub',
    seedUrl: 'https://www.nbc.ca/personal/switch-national-bank/occupations/healthcare.html',
    country: 'CA',
    audience: 'Canadian healthcare professionals',
    offerTypeHint: 'bundle',
    captureType: 'profession-hub',
    onboardingStatus: 'active-parser',
    verificationStatus: 'confirmed',
    official: true,
    notes: 'Primary National Bank healthcare landing page already tracked by the updater.'
  },
  {
    id: 'nbc-healthcare-professionals',
    provider: 'National Bank',
    title: 'Healthcare professionals banking offer',
    category: 'banking',
    subcategory: 'profession page',
    seedUrl: 'https://www.nbc.ca/personal/switch-national-bank/occupations/healthcare/healthcare-professionals.html',
    country: 'CA',
    audience: 'Physicians, dentists, veterinarians, optometrists, pharmacists and allied clinical owners',
    offerTypeHint: 'bundle',
    captureType: 'offer-page',
    onboardingStatus: 'queued',
    verificationStatus: 'inferred',
    official: true,
    notes: 'Official National Bank occupation-page pattern; validate live before activating extraction.'
  },
  {
    id: 'nbc-health-sciences',
    provider: 'National Bank',
    title: 'Health sciences specialists offer',
    category: 'banking',
    subcategory: 'profession page',
    seedUrl: 'https://www.nbc.ca/personal/switch-national-bank/occupations/healthcare/health-sciences.html',
    country: 'CA',
    audience: 'Nurses and allied health professionals',
    offerTypeHint: 'bundle',
    captureType: 'offer-page',
    onboardingStatus: 'active-parser',
    verificationStatus: 'confirmed',
    official: true,
    notes: 'Official health-sciences page already tracked by the updater.'
  },
  {
    id: 'scotia-healthcare-plus',
    provider: 'Scotiabank',
    title: 'Healthcare+ hub',
    category: 'banking',
    subcategory: 'program hub',
    seedUrl: 'https://www.scotiabank.com/ca/en/healthcare-plus.html',
    country: 'CA',
    audience: 'Canadian healthcare professionals',
    offerTypeHint: 'bundle',
    captureType: 'program-hub',
    onboardingStatus: 'queued',
    verificationStatus: 'inferred',
    official: true,
    notes: 'Program-level hub for physician and dental banking offers.'
  },
  {
    id: 'scotia-physician-banking-hub',
    provider: 'Scotiabank',
    title: 'Physician Banking hub',
    category: 'banking',
    subcategory: 'program hub',
    seedUrl: 'https://www.scotiabank.com/ca/en/healthcare-plus/physician-banking.html',
    country: 'CA',
    audience: 'Physicians, students and residents',
    offerTypeHint: 'bundle',
    captureType: 'program-hub',
    onboardingStatus: 'queued',
    verificationStatus: 'inferred',
    official: true,
    notes: 'Entry point for student, resident and practising-physician offer pages.'
  },
  {
    id: 'scotia-medical-students',
    provider: 'Scotiabank',
    title: 'Medical students banking offer',
    category: 'lending',
    subcategory: 'student line of credit',
    seedUrl: 'https://www.scotiabank.com/ca/en/healthcare-plus/physician-banking/medical-students.html',
    country: 'CA',
    audience: 'Medical students',
    offerTypeHint: 'rate',
    captureType: 'offer-page',
    onboardingStatus: 'active-parser',
    verificationStatus: 'confirmed',
    official: true,
    notes: 'Confirmed official Scotiabank page with student LOC and banking perks.'
  },
  {
    id: 'scotia-medical-residents',
    provider: 'Scotiabank',
    title: 'Medical residents banking offer',
    category: 'lending',
    subcategory: 'resident line of credit',
    seedUrl: 'https://www.scotiabank.com/ca/en/healthcare-plus/physician-banking/medical-residents.html',
    country: 'CA',
    audience: 'Medical residents',
    offerTypeHint: 'rate',
    captureType: 'offer-page',
    onboardingStatus: 'active-parser',
    verificationStatus: 'confirmed',
    official: true,
    notes: 'Confirmed official Scotiabank resident page with borrowing and credit-card offers.'
  },
  {
    id: 'scotia-practising-physicians-personal',
    provider: 'Scotiabank',
    title: 'Practising physicians personal banking',
    category: 'banking',
    subcategory: 'physician banking',
    seedUrl: 'https://www.scotiabank.com/ca/en/healthcare-plus/physician-banking/practising/personal-banking.html',
    country: 'CA',
    audience: 'Practising physicians',
    offerTypeHint: 'bundle',
    captureType: 'offer-page',
    onboardingStatus: 'active-parser',
    verificationStatus: 'confirmed',
    official: true,
    notes: 'Confirmed official practising-physicians page already parsed weekly.'
  },
  {
    id: 'rbc-healthcare-hub',
    provider: 'RBC',
    title: 'Healthcare Financial Solutions hub',
    category: 'banking',
    subcategory: 'program hub',
    seedUrl: 'https://www.rbcroyalbank.com/healthcare-financial-solutions/',
    country: 'CA',
    audience: 'Students, residents, physicians, dentists and other healthcare providers',
    offerTypeHint: 'bundle',
    captureType: 'program-hub',
    onboardingStatus: 'queued',
    verificationStatus: 'confirmed',
    official: true,
    notes: 'Confirmed official RBC healthcare hub linking to the main profession pages.'
  },
  {
    id: 'rbc-healthcare-advantage',
    provider: 'RBC',
    title: 'RBC Healthcare Advantage',
    category: 'banking',
    subcategory: 'banking bundle',
    seedUrl: 'https://www.rbcroyalbank.com/healthcare-financial-solutions/solutions/rbc-healthcare-advantage.html',
    country: 'CA',
    audience: 'Healthcare students and professionals',
    offerTypeHint: 'bundle',
    captureType: 'offer-page',
    onboardingStatus: 'active-parser',
    verificationStatus: 'confirmed',
    official: true,
    notes: 'Confirmed official RBC Healthcare Advantage page with banking and borrowing benefits.'
  },
  {
    id: 'rbc-medical-dental-students',
    provider: 'RBC',
    title: 'Medical and dental students',
    category: 'lending',
    subcategory: 'student line of credit',
    seedUrl: 'https://www.rbcroyalbank.com/healthcare-financial-solutions/medical-dental-students.html',
    country: 'CA',
    audience: 'Medical and dental students',
    offerTypeHint: 'rate',
    captureType: 'offer-page',
    onboardingStatus: 'active-parser',
    verificationStatus: 'confirmed',
    official: true,
    notes: 'Confirmed official RBC page with student borrowing and banking offers.'
  },
  {
    id: 'rbc-medical-dental-residents',
    provider: 'RBC',
    title: 'Medical and dental residents',
    category: 'lending',
    subcategory: 'resident financing',
    seedUrl: 'https://www.rbcroyalbank.com/healthcare-financial-solutions/medical-dental-residents.html',
    country: 'CA',
    audience: 'Medical and dental residents',
    offerTypeHint: 'rate',
    captureType: 'offer-page',
    onboardingStatus: 'active-parser',
    verificationStatus: 'inferred',
    official: true,
    notes: 'URL follows RBC healthcare page naming and should be validated before parser activation.'
  },
  {
    id: 'rbc-physicians',
    provider: 'RBC',
    title: 'Financial planning for physicians',
    category: 'banking',
    subcategory: 'physician banking',
    seedUrl: 'https://www.rbcroyalbank.com/healthcare-financial-solutions/practising-professionals/physicians.html',
    country: 'CA',
    audience: 'Physicians',
    offerTypeHint: 'bundle',
    captureType: 'offer-page',
    onboardingStatus: 'active-parser',
    verificationStatus: 'confirmed',
    official: true,
    notes: 'Confirmed official RBC physician page with current limited-time financing and Avion offer details.'
  },
  {
    id: 'rbc-dentists',
    provider: 'RBC',
    title: 'Financial planning for dentists',
    category: 'banking',
    subcategory: 'dentist banking',
    seedUrl: 'https://www.rbcroyalbank.com/healthcare-financial-solutions/practising-professionals/dentists.html',
    country: 'CA',
    audience: 'Dentists',
    offerTypeHint: 'bundle',
    captureType: 'offer-page',
    onboardingStatus: 'active-parser',
    verificationStatus: 'confirmed',
    official: true,
    notes: 'Confirmed official RBC dentist page with current limited-time financing and Avion offer details.'
  },
  {
    id: 'cibc-healthcare-hub',
    provider: 'CIBC',
    title: 'Healthcare Banking hub',
    category: 'banking',
    subcategory: 'program hub',
    seedUrl: 'https://www.cibc.com/en/business/banking-for-professionals/healthcare.html',
    country: 'CA',
    audience: 'Healthcare professionals',
    offerTypeHint: 'bundle',
    captureType: 'program-hub',
    onboardingStatus: 'queued',
    verificationStatus: 'confirmed',
    official: true,
    notes: 'Confirmed official CIBC healthcare hub covering physicians, dentists, internationally trained dentists and optometrists.'
  },
  {
    id: 'cibc-physicians',
    provider: 'CIBC',
    title: 'Banking for physicians',
    category: 'banking',
    subcategory: 'physician banking',
    seedUrl: 'https://www.cibc.com/en/business/banking-for-professionals/healthcare/physicians.html',
    country: 'CA',
    audience: 'Physicians',
    offerTypeHint: 'bundle',
    captureType: 'offer-page',
    onboardingStatus: 'queued',
    verificationStatus: 'inferred',
    official: true,
    notes: 'Path is inferred from the CIBC healthcare hub structure and should be live-checked before activation.'
  },
  {
    id: 'cibc-dentists',
    provider: 'CIBC',
    title: 'Banking for dentists',
    category: 'banking',
    subcategory: 'dentist banking',
    seedUrl: 'https://www.cibc.com/en/business/banking-for-professionals/dentists.html',
    country: 'CA',
    audience: 'Dentists',
    offerTypeHint: 'bundle',
    captureType: 'offer-page',
    onboardingStatus: 'queued',
    verificationStatus: 'confirmed',
    official: true,
    notes: 'Confirmed official CIBC dentist page with business banking, cards and investment perks.'
  },
  {
    id: 'cibc-optometry',
    provider: 'CIBC',
    title: 'Banking for optometrists',
    category: 'banking',
    subcategory: 'optometry banking',
    seedUrl: 'https://www.cibc.com/en/business/banking-for-professionals/optometry.html',
    country: 'CA',
    audience: 'Optometrists',
    offerTypeHint: 'bundle',
    captureType: 'offer-page',
    onboardingStatus: 'queued',
    verificationStatus: 'inferred',
    official: true,
    notes: 'Expected official CIBC profession page based on site taxonomy; confirm before parser activation.'
  },
  {
    id: 'cibc-internationally-trained-dentists',
    provider: 'CIBC',
    title: 'Banking for internationally trained dentists',
    category: 'banking',
    subcategory: 'dentist banking',
    seedUrl: 'https://www.cibc.com/en/business/banking-for-professionals/internationally-trained-dentists.html',
    country: 'CA',
    audience: 'Internationally trained dentists',
    offerTypeHint: 'bundle',
    captureType: 'offer-page',
    onboardingStatus: 'queued',
    verificationStatus: 'inferred',
    official: true,
    notes: 'Path is inferred from the healthcare hub profession links and should be confirmed before onboarding.'
  },
  {
    id: 'td-healthcare-business',
    provider: 'TD',
    title: 'Banking for healthcare professionals',
    category: 'banking',
    subcategory: 'practice banking',
    seedUrl: 'https://www.td.com/ca/en/business-banking/solutions/small-business/professional-banking/banking-for-healthcare-professionals',
    country: 'CA',
    audience: 'Physicians, dentists, veterinarians and optometrists',
    offerTypeHint: 'bundle',
    captureType: 'offer-page',
    onboardingStatus: 'queued',
    verificationStatus: 'confirmed',
    official: true,
    notes: 'Confirmed official TD healthcare-business page with financing, accounts and practice support.'
  },
  {
    id: 'td-professional-student-loc',
    provider: 'TD',
    title: 'Professional student line of credit',
    category: 'lending',
    subcategory: 'student line of credit',
    seedUrl: 'https://www.td.com/ca/en/personal-banking/products/borrowing/lines-of-credit/professional-student-line-of-credit',
    country: 'CA',
    audience: 'Professional students including healthcare fields',
    offerTypeHint: 'rate',
    captureType: 'offer-page',
    onboardingStatus: 'queued',
    verificationStatus: 'inferred',
    official: true,
    notes: 'Official TD line-of-credit path pattern; verify the current page copy before parsing.'
  },
  {
    id: 'td-professional-student-package',
    provider: 'TD',
    title: 'Professional student package',
    category: 'banking',
    subcategory: 'student banking',
    seedUrl: 'https://www.td.com/ca/en/personal-banking/solutions/student-banking/grad-professional-student-solutions',
    country: 'CA',
    audience: 'Professional students including medicine and dentistry',
    offerTypeHint: 'bundle',
    captureType: 'offer-page',
    onboardingStatus: 'queued',
    verificationStatus: 'inferred',
    official: true,
    notes: 'Official TD student-banking pattern; confirm live offer language before activation.'
  },
  {
    id: 'td-wealth-students-residents',
    provider: 'TD',
    title: 'TD Wealth for students and residents',
    category: 'investing',
    subcategory: 'wealth planning',
    seedUrl: 'https://www.td.com/ca/en/investing/wealth/healthcare-professionals/students-and-residents',
    country: 'CA',
    audience: 'Dental and medical students and residents',
    offerTypeHint: 'service',
    captureType: 'offer-page',
    onboardingStatus: 'queued',
    verificationStatus: 'confirmed',
    official: true,
    notes: 'Confirmed official TD Wealth page for students and residents with banking and planning support.'
  },
  {
    id: 'td-wealth-dentists-physicians',
    provider: 'TD',
    title: 'TD Wealth for dentists and practising physicians',
    category: 'investing',
    subcategory: 'wealth planning',
    seedUrl: 'https://www.td.com/ca/en/investing/wealth/healthcare-professionals/dentists-and-practising-physicians',
    country: 'CA',
    audience: 'Dentists and practising physicians',
    offerTypeHint: 'service',
    captureType: 'offer-page',
    onboardingStatus: 'queued',
    verificationStatus: 'confirmed',
    official: true,
    notes: 'Confirmed official TD Wealth page describing preferred banking, credit and planning support.'
  },
  {
    id: 'td-wealth-retired-physicians',
    provider: 'TD',
    title: 'TD Wealth for retired dentists and physicians',
    category: 'investing',
    subcategory: 'retirement planning',
    seedUrl: 'https://www.td.com/ca/en/investing/wealth/healthcare-professionals/retired-physicians',
    country: 'CA',
    audience: 'Retired dentists and physicians',
    offerTypeHint: 'service',
    captureType: 'offer-page',
    onboardingStatus: 'queued',
    verificationStatus: 'confirmed',
    official: true,
    notes: 'Confirmed official TD Wealth retirement page for healthcare professionals.'
  },
  {
    id: 'bmo-student-borrowing-hub',
    provider: 'BMO',
    title: 'Student borrowing hub',
    category: 'lending',
    subcategory: 'student borrowing',
    seedUrl: 'https://www.bmo.com/main/personal/loans-line-of-credit/student-borrowing/',
    country: 'CA',
    audience: 'Students, including healthcare professions',
    offerTypeHint: 'rate',
    captureType: 'program-hub',
    onboardingStatus: 'queued',
    verificationStatus: 'inferred',
    official: true,
    notes: 'BMO hub for student borrowing products; expected to route into profession-specific healthcare pages.'
  },
  {
    id: 'bmo-professional-student-loc',
    provider: 'BMO',
    title: 'Professional student line of credit',
    category: 'lending',
    subcategory: 'student line of credit',
    seedUrl: 'https://www.bmo.com/main/personal/loans-line-of-credit/student-borrowing/professional-student-line-of-credit/',
    country: 'CA',
    audience: 'Professional students',
    offerTypeHint: 'rate',
    captureType: 'offer-page',
    onboardingStatus: 'queued',
    verificationStatus: 'inferred',
    official: true,
    notes: 'Official BMO path pattern for profession-focused student lending; confirm before activation.'
  },
  {
    id: 'bmo-medical-dental-loc',
    provider: 'BMO',
    title: 'Medical and dental student line of credit',
    category: 'lending',
    subcategory: 'student line of credit',
    seedUrl: 'https://www.bmo.com/main/personal/loans-line-of-credit/student-borrowing/medical-dental-student-line-of-credit/',
    country: 'CA',
    audience: 'Medical and dental students',
    offerTypeHint: 'rate',
    captureType: 'offer-page',
    onboardingStatus: 'queued',
    verificationStatus: 'inferred',
    official: true,
    notes: 'Likely official BMO healthcare-student LOC page; validate before onboarding.'
  },
  {
    id: 'desjardins-offers-hub',
    provider: 'Desjardins',
    title: 'Offers directory',
    category: 'banking',
    subcategory: 'offers hub',
    seedUrl: 'https://www.desjardins.com/en/offers.html',
    country: 'CA',
    audience: 'Canadian consumers and professionals',
    offerTypeHint: 'bundle',
    captureType: 'program-hub',
    onboardingStatus: 'queued',
    verificationStatus: 'confirmed',
    official: true,
    notes: 'Confirmed official Desjardins offers directory with a professionals segment.'
  },
  {
    id: 'desjardins-nurses',
    provider: 'Desjardins',
    title: 'Offer for nurses',
    category: 'banking',
    subcategory: 'profession bundle',
    seedUrl: 'https://www.desjardins.com/en/offers/professionals/nurse.html',
    country: 'CA',
    audience: 'Nurses',
    offerTypeHint: 'bundle',
    captureType: 'offer-page',
    onboardingStatus: 'queued',
    verificationStatus: 'inferred',
    official: true,
    notes: 'Follows confirmed Desjardins profession-page pattern and should be validated live before parsing.'
  },
  {
    id: 'desjardins-pharmacists',
    provider: 'Desjardins',
    title: 'Offer for pharmacists',
    category: 'banking',
    subcategory: 'profession bundle',
    seedUrl: 'https://www.desjardins.com/en/offers/professionals/pharmacist.html',
    country: 'CA',
    audience: 'Pharmacists',
    offerTypeHint: 'bundle',
    captureType: 'offer-page',
    onboardingStatus: 'queued',
    verificationStatus: 'confirmed',
    official: true,
    notes: 'Confirmed official Desjardins pharmacist page with discounted account, credit-card and line-of-credit perks.'
  },
  {
    id: 'desjardins-resident-doctors',
    provider: 'Desjardins',
    title: 'Offer for resident doctors',
    category: 'banking',
    subcategory: 'profession bundle',
    seedUrl: 'https://www.desjardins.com/en/offers/professionals/resident-doctor.html',
    country: 'CA',
    audience: 'Resident doctors',
    offerTypeHint: 'bundle',
    captureType: 'offer-page',
    onboardingStatus: 'queued',
    verificationStatus: 'inferred',
    official: true,
    notes: 'Expected Desjardins profession page for resident doctors; verify before activation.'
  },
  {
    id: 'desjardins-medical-specialists',
    provider: 'Desjardins',
    title: 'Offer for medical specialists',
    category: 'banking',
    subcategory: 'profession bundle',
    seedUrl: 'https://www.desjardins.com/en/offers/professionals/medical-specialist.html',
    country: 'CA',
    audience: 'Medical specialists',
    offerTypeHint: 'bundle',
    captureType: 'offer-page',
    onboardingStatus: 'queued',
    verificationStatus: 'confirmed',
    official: true,
    notes: 'Confirmed official Desjardins medical-specialist page with account, card and line-of-credit benefits.'
  },
  {
    id: 'desjardins-pharmacist-owners',
    provider: 'Desjardins',
    title: 'Offer for pharmacist-owners',
    category: 'banking',
    subcategory: 'profession bundle',
    seedUrl: 'https://www.desjardins.com/ca/personal/you-are/professionals/pharmacist-owners/index.jsp',
    country: 'CA',
    audience: 'Pharmacist-owners',
    offerTypeHint: 'bundle',
    captureType: 'offer-page',
    onboardingStatus: 'queued',
    verificationStatus: 'confirmed',
    official: true,
    notes: 'Confirmed official Desjardins pharmacist-owner page with bundled banking and reduced lending rates.'
  },
  {
    id: 'lenovo-ca-discount-programs',
    provider: 'Lenovo',
    title: 'Discount programs hub',
    category: 'tech',
    subcategory: 'employee discount program',
    seedUrl: 'https://www.lenovo.com/ca/en/discount-programs',
    country: 'CA',
    audience: 'Canadian public-sector and professional groups, including healthcare workers',
    offerTypeHint: 'discount',
    captureType: 'program-hub',
    onboardingStatus: 'queued',
    verificationStatus: 'inferred',
    official: true,
    notes: 'Canadian Lenovo discount-program hub; confirm the healthcare entry path before activation.'
  },
  {
    id: 'samsung-ca-offers-program',
    provider: 'Samsung',
    title: 'Samsung offers program',
    category: 'tech',
    subcategory: 'employee purchase program',
    seedUrl: 'https://www.samsung.com/ca/offer/offers-program/',
    country: 'CA',
    audience: 'Eligible groups including healthcare professionals',
    offerTypeHint: 'discount',
    captureType: 'program-hub',
    onboardingStatus: 'queued',
    verificationStatus: 'inferred',
    official: true,
    notes: 'Official Canadian Samsung offers-program hub; confirm healthcare-worker eligibility before parsing.'
  },
  {
    id: 'under-armour-healthcare-discount',
    provider: 'Under Armour',
    title: 'Healthcare worker discount',
    category: 'perks',
    subcategory: 'apparel discount',
    seedUrl: 'https://www.underarmour.ca/en-ca/c/healthcare-discount/',
    country: 'CA',
    audience: 'Healthcare workers',
    offerTypeHint: 'discount',
    captureType: 'offer-page',
    onboardingStatus: 'queued',
    verificationStatus: 'inferred',
    official: true,
    notes: 'Official Canadian Under Armour path pattern for healthcare-worker discounts; verify current terms before activation.'
  },
  {
    id: 'gmc-preferred-pricing',
    provider: 'GMC',
    title: 'Preferred pricing programs',
    category: 'auto',
    subcategory: 'vehicle discount program',
    seedUrl: 'https://www.gmccanada.ca/en/programs/preferred-pricing',
    country: 'CA',
    audience: 'Eligible affinity and employer groups, including some healthcare workers',
    offerTypeHint: 'discount',
    captureType: 'program-hub',
    onboardingStatus: 'active-parser',
    verificationStatus: 'confirmed',
    official: true,
    notes: 'GM-brand program page already used as a live parser source for automotive discounts.'
  },
  {
    id: 'chevrolet-preferred-pricing',
    provider: 'Chevrolet',
    title: 'Preferred pricing programs',
    category: 'auto',
    subcategory: 'vehicle discount program',
    seedUrl: 'https://www.chevrolet.ca/en/programs/preferred-pricing',
    country: 'CA',
    audience: 'Eligible affinity and employer groups, including some healthcare workers',
    offerTypeHint: 'discount',
    captureType: 'program-hub',
    onboardingStatus: 'queued',
    verificationStatus: 'inferred',
    official: true,
    notes: 'Official Chevrolet Canada preferred-pricing pattern; confirm the healthcare-specific route before onboarding.'
  },
  {
    id: 'cadillac-preferred-pricing',
    provider: 'Cadillac',
    title: 'Preferred pricing programs',
    category: 'auto',
    subcategory: 'vehicle discount program',
    seedUrl: 'https://www.cadillaccanada.ca/en/programs/preferred-pricing',
    country: 'CA',
    audience: 'Eligible affinity and employer groups, including some healthcare workers',
    offerTypeHint: 'discount',
    captureType: 'program-hub',
    onboardingStatus: 'queued',
    verificationStatus: 'inferred',
    official: true,
    notes: 'Official Cadillac Canada preferred-pricing pattern; validate healthcare-specific eligibility before parsing.'
  }
];

export const curatedSourceCatalog: SourceCatalogEntry[] = rawSourceCatalog.map((entry) => ({
  ...entry,
  onboardingStatus: 'active-parser'
}));
